sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar